const gate = document.getElementById("invitationGate");
const openBtn = document.getElementById("openInvitation");
const music = document.getElementById("bgMusic");
const soundToggle = document.getElementById("soundToggle");
const pageMusicToggle = document.getElementById("pageMusicToggle");
let soundOn = false;
function syncMusicButtons(){const label=soundOn?"♫ Music On":"♪ Play Music";[soundToggle,pageMusicToggle].filter(Boolean).forEach(btn=>{btn.textContent=label;btn.setAttribute("aria-label",soundOn?"Pause background music":"Play background music")})}
openBtn.addEventListener("click",()=>{gate.classList.add("opened");document.body.classList.remove("locked");setTimeout(()=>{gate.style.display="none"},1150)});
async function toggleMusic(e){e?.stopPropagation();if(music.paused){try{await music.play();soundOn=true}catch(_){soundOn=false}}else{music.pause();soundOn=false}syncMusicButtons()}
soundToggle?.addEventListener("click",toggleMusic);pageMusicToggle?.addEventListener("click",toggleMusic);syncMusicButtons();
function updateCountdown(){const target=new Date(document.getElementById("countdown").dataset.date).getTime();const diff=Math.max(0,target-Date.now());const sec=Math.floor(diff/1000);document.getElementById("days").textContent=String(Math.floor(sec/86400)).padStart(2,"0");document.getElementById("hours").textContent=String(Math.floor((sec%86400)/3600)).padStart(2,"0");document.getElementById("minutes").textContent=String(Math.floor((sec%3600)/60)).padStart(2,"0");document.getElementById("seconds").textContent=String(sec%60).padStart(2,"0")}
updateCountdown();setInterval(updateCountdown,1000);
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll(".reveal-on-scroll").forEach(el=>observer.observe(el));
function makePetal(){if(document.hidden||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const p=document.createElement("i");p.className="petal";p.style.left=Math.random()*100+"vw";p.style.animationDuration=(9+Math.random()*7)+"s";p.style.setProperty("--drift",(-70+Math.random()*140)+"px");p.style.transform=`rotate(${Math.random()*360}deg) scale(${.55+Math.random()*.5})`;document.getElementById("petals").appendChild(p);setTimeout(()=>p.remove(),16500)}
setInterval(makePetal,1500);for(let i=0;i<4;i++)setTimeout(makePetal,i*450);
const dialog=document.getElementById("lightbox"),lightboxImage=document.getElementById("lightboxImage");document.querySelectorAll(".gallery-item img").forEach(img=>img.parentElement.addEventListener("click",()=>{lightboxImage.src=img.currentSrc||img.src;lightboxImage.alt=img.alt;dialog.showModal()}));document.getElementById("closeLightbox").addEventListener("click",()=>dialog.close());dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()});
const form=document.getElementById("rsvpForm");form.addEventListener("submit",e=>{e.preventDefault();const name=document.getElementById("guestName").value.trim(),count=document.getElementById("guestCount").value,events=[...form.querySelectorAll('input[name="events"]:checked')].map(x=>x.value),food=document.getElementById("foodPreference").value,help=document.getElementById("travelHelp").value,note=document.getElementById("guestMessage").value.trim(),attending=events.length?events.join("; "):"No events selected / not sure yet";const plain=`Wedding RSVP\n\nName: ${name}\nGuests: ${count}\nCelebrations: ${attending}\nFood: ${food}\nStay/Travel Help: ${help}\nMessage: ${note||"-"}`;window.open(`https://wa.me/918256995690?text=${encodeURIComponent(plain)}`,"_blank","noopener");document.getElementById("formStatus").textContent="Opening WhatsApp…"});
